version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: unofficial.ScintillaNET
    versions:
    - 3.8.1
    - 3.8.2
    - 3.8.3
    - 3.8.4
    - 3.8.5
  - dependency-name: VPKSoft.ScintillaLexers
    versions:
    - 1.1.2
